name: Deploy Prod Environment

on:
  #push:
  workflow_dispatch:
    # branches:
    # - main
    # paths:
    #  - "env/prod/**" # <--- ONLY run if Prod files change
    # Note: We do NOT trigger on 'modules/**' for Prod automatically.
    # Best Practice: Test modules in Dev first, then manually sync Prod.

jobs:
  terraform:
    name: "Prod: Plan & Apply"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    defaults:
      run:
        working-directory: ./env/prod # <--- CRITICAL: Run inside PROD folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize (Connects to Prod Bucket)
      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      - name: Terraform Validate
        run: terraform validate

      # Strict Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      # Strict Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false tfplan
